# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .gitpod/.gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Setup environment
    init: |
      docker-compose -f .gitpod/docker-compose.yml pull
      ./wp-site-setup.sh
  - name: Start environment
    command: |
      docker-compose -f .gitpod/docker-compose.yml up -d
      exec zsh
      bash -lic 'true'

gitConfig:
  safe.directory: "/workspace/wordpress-development"
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: WordPress
    description: Port 8000 for WordPress
    port: 8000
    onOpen: ignore
  - name: MySQL
    description: Port 8080 for the adminer
    port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - claudiosanches.woocommerce
    - closemarketing.wp-development-toolbox
    - DavidAnson.vscode-markdownlint
    - DEVSENSE.composer-php-vscode
    - DEVSENSE.phptools-vscode
    - DEVSENSE.profiler-php-vscode
    - esbenp.prettier-vscode
    - getpsalm.psalm-vscode-plugin
    - howardzuo.vscode-git-tags
    - junstyle.php-cs-fixer
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
    - rangav.vscode-thunder-client
    - redhat.vscode-xml
    - stanislav.vscode-twig
    - xdebug.php-debug
additionalRepositories:
  - url: https://github.com/Nziswano/docfox-hubspot-plugin.git
    checkoutLocation: docfox-plugin
mainConfiguration: https://github.com/johanmartindev/wordpress-development.git
