# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .gitpod/.gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: |
      echo "alias wp-site='wp server --port=8000 --debug --color --host=127.0.0.1'" >> ~/.zshrc
      docker-compose -f .gitpod/docker-compose.yml pull
    command: |
      docker-compose -f .gitpod/docker-compose.yml up -d
gitConfig:
  safe.directory: "/workspace/wordpress-development"
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: WordPress
    description: Port 8000 for WordPress
    port: 8000
    onOpen: ignore
  - name: Adminer
    description: Port 8080 for the adminer
    port: 8080
    onOpen: ignore
  - name: MySQL
    description: Port 8080 for the adminer
    port: 3306
    onOpen: ignore
vscode:
  extensions:
    - AmazonWebServices.aws-toolkit-vscode
    - bmewburn.vscode-intelephense-client
    - DEVSENSE.composer-php-vscode
    - DEVSENSE.phptools-vscode
    - DEVSENSE.profiler-php-vscode
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
    - xdebug.php-debug
    - closemarketing.wp-development-toolbox
    - claudiosanches.woocommerce
    - junstyle.php-cs-fixer
additionalRepositories:
  - url: https://github.com/johanmartindev/docfox-hubspot-plugin.git
    checkoutLocation: docfox-plugin
mainConfiguration: https://github.com/johanmartindev/wordpress-development.git
github:
  prebuilds:
    addBadge: true
    addComment: true
