version: '3.8'
services:
  wordpressdb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./scripts/test-db.sql:/docker-entrypoint-initdb.d/test-db.sql
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
volumes:
  mariadb-data: null
